Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 70
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	7	aggregate_data_summary
	70	align
	1	all
	70	create_blocks
	70	merge_fastq
	218
Resources before job selection: {'_cores': 70, '_nodes': 9223372036854775807}
Ready jobs (70):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Selected jobs (70):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775737}

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip1/barcode25/9/fastq_files.lst
    jobid: 30
    wildcards: chip=Chip1, native=barcode25, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip1/barcode30/8/fastq_files.lst
    jobid: 9
    wildcards: chip=Chip1, native=barcode30, block=8


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip1/barcode25/1/fastq_files.lst
    jobid: 22
    wildcards: chip=Chip1, native=barcode25, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip1/barcode31/8/fastq_files.lst
    jobid: 19
    wildcards: chip=Chip1, native=barcode31, block=8


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip1/barcode25/5/fastq_files.lst
    jobid: 26
    wildcards: chip=Chip1, native=barcode25, block=5


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip2/barcode29/0/fastq_files.lst
    jobid: 31
    wildcards: chip=Chip2, native=barcode29, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz             | head -n 100 > results/Chip2/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/0/fastq_files.lst
        rm -f results/Chip2/barcode29/0/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip2/barcode27/0/fastq_files.lst
    jobid: 41
    wildcards: chip=Chip2, native=barcode27, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip2/barcode26/0/fastq_files.lst
    jobid: 51
    wildcards: chip=Chip2, native=barcode26, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp
        

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip2/barcode27/1/fastq_files.lst
    jobid: 42
    wildcards: chip=Chip2, native=barcode27, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp
        
[Tue Apr 22 13:31:45 2025]
Finished job 31.
1 of 218 steps (0.46%) done

[Tue Apr 22 13:31:45 2025]
rule create_blocks:
    output: results/Chip2/barcode29/3/fastq_files.lst
    jobid: 34
    wildcards: chip=Chip2, native=barcode29, block=3


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz             | head -n 100 > results/Chip2/barcode29/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode29/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/3/fastq_files.lst
        rm -f results/Chip2/barcode29/3/fastq_files.lst.temp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp' returned non-zero exit status 141.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 41
    output: results/Chip2/barcode27/0/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
[Tue Apr 22 13:31:45 2025]

Error in rule create_blocks:
    jobid: 51
    output: results/Chip2/barcode26/0/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode27/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/0/fastq_files.lst
        rm -f results/Chip2/barcode27/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
[Tue Apr 22 13:31:45 2025]
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp' returned non-zero exit status 141.

Finished job 34.
2 of 218 steps (0.92%) done
[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 42
    output: results/Chip2/barcode27/1/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip2/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/1/fastq_files.lst
        rm -f results/Chip2/barcode27/1/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 19
    output: results/Chip1/barcode31/8/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode31/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/8/fastq_files.lst
        rm -f results/Chip1/barcode31/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 30
    output: results/Chip1/barcode25/9/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode25/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/9/fastq_files.lst
        rm -f results/Chip1/barcode25/9/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 9
    output: results/Chip1/barcode30/8/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode30/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/8/fastq_files.lst
        rm -f results/Chip1/barcode30/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp' returned non-zero exit status 141.

Job failed, going on with independent jobs.
[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 22
    output: results/Chip1/barcode25/1/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode25/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/1/fastq_files.lst
        rm -f results/Chip1/barcode25/1/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 13:31:45 2025]
Error in rule create_blocks:
    jobid: 26
    output: results/Chip1/barcode25/5/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode25/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/5/fastq_files.lst
        rm -f results/Chip1/barcode25/5/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode30/1/fastq_files.lst
    jobid: 2
    wildcards: chip=Chip1, native=barcode30, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode31/9/fastq_files.lst
    jobid: 20
    wildcards: chip=Chip1, native=barcode31, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip2/barcode27/3/fastq_files.lst
    jobid: 44
    wildcards: chip=Chip2, native=barcode27, block=3


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode25/8/fastq_files.lst
    jobid: 29
    wildcards: chip=Chip1, native=barcode25, block=8


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode30/9/fastq_files.lst
    jobid: 10
    wildcards: chip=Chip1, native=barcode30, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp' returned non-zero exit status 141.


[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode31/5/fastq_files.lst
    jobid: 16
    wildcards: chip=Chip1, native=barcode31, block=5
[Tue Apr 22 13:31:46 2025]

Error in rule create_blocks:

        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp
        
    jobid: 44
    output: results/Chip2/barcode27/3/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip1/barcode31/1/fastq_files.lst
    jobid: 12
    wildcards: chip=Chip1, native=barcode31, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp
        
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode27/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/3/fastq_files.lst
        rm -f results/Chip2/barcode27/3/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip2/barcode26/3/fastq_files.lst
    jobid: 54
    wildcards: chip=Chip2, native=barcode26, block=3


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip2/barcode28/4/fastq_files.lst
    jobid: 65
    wildcards: chip=Chip2, native=barcode28, block=4


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp
        

[Tue Apr 22 13:31:46 2025]
rule create_blocks:
    output: results/Chip2/barcode28/6/fastq_files.lst
    jobid: 67
    wildcards: chip=Chip2, native=barcode28, block=6


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip2/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/6/fastq_files.lst
        rm -f results/Chip2/barcode28/6/fastq_files.lst.temp
        
Terminating processes on user request, this might take some time.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
[Tue Apr 22 13:31:46 2025]
Error in rule create_blocks:
Error in rule create_blocks:
[Tue Apr 22 13:31:46 2025]
Error in rule create_blocks:
Error in rule create_blocks:
Error in rule create_blocks:
Error in rule create_blocks:
Error in rule create_blocks:
    jobid: 20
    jobid: 65
Error in rule create_blocks:
    jobid: 16
    jobid: 29
    jobid: 2
    jobid: 54
    jobid: 10
    output: results/Chip1/barcode31/9/fastq_files.lst
    output: results/Chip2/barcode28/4/fastq_files.lst
    jobid: 12
    output: results/Chip1/barcode31/5/fastq_files.lst
    output: results/Chip1/barcode25/8/fastq_files.lst
    output: results/Chip1/barcode30/1/fastq_files.lst
    output: results/Chip2/barcode26/3/fastq_files.lst
    output: results/Chip1/barcode30/9/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    output: results/Chip1/barcode31/1/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)






Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/4/fastq_files.lst
        rm -f results/Chip2/barcode28/4/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode31/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/9/fastq_files.lst
        rm -f results/Chip1/barcode31/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode31/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/5/fastq_files.lst
        rm -f results/Chip1/barcode31/5/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode30/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/1/fastq_files.lst
        rm -f results/Chip1/barcode30/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode31/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/1/fastq_files.lst
        rm -f results/Chip1/barcode31/1/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz             | head -n 100 > results/Chip2/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/3/fastq_files.lst
        rm -f results/Chip2/barcode26/3/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Job failed, going on with independent jobs.
Complete log: /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/.snakemake/log/2025-04-22T133145.012784.snakemake.log
unlocking
removing lock
removing lock
removed all locks
